version: "3.5"
services:
  milvus:
    container_name: milvus
    image: milvusdb/milvus:latest
    restart: always
    ports:
      - "19530:19530"
    volumes:
      - ./milvus_data:/var/lib/milvus
    environment:
      - CACHE_SIZE=4GB
      - METRICS_LEVEL=debug
