version: "3.5"
services:
  milvus:
    container_name: milvus
    image: milvusdb/milvus:latest
    restart: always
    ports:
      - "19530:19530"
    volumes:
      - milvus_data:/var/lib/milvus
    environment:
      - MILVUS_CACHE_NODE_MAX_MEMORY=4GB
      - MILVUS_LOG_LEVEL=debug

  fastapi-app:
    container_name: fastapi-app
    build: .
    restart: always
    ports:
      - "8001:8001"  # Ensure it matches your FastAPI app port
    depends_on:
      - milvus
    environment:
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530

volumes:
  milvus_data:
